services:
  server:
    build:
      context: ./server
      target: dev
      args:
        - PORT = ${PORT}
    environment:
      NODE_ENV: development
    ports:
      - 3001:${PORT}
      - 9229:9229
    env_file:
      - .env
    volumes:
      - ./server:/app