services:
  server:
    build:
      context: ./server
      target: dev
    environment:
      NODE_ENV: development
    ports:
      - "8000:5000"
    volumes:
      - ./server:/app
#      - /app/node_modules