services:
  server:
    build:
      context: ./server
      target: dev
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    env_file:
      - .env
    volumes:
      - ./server:/app
