@path={{envPath}}{{$dotenv SERVER_PORT}}/account


POST {{path}}/register
Content-Type: application/json

{
    "email":"aa@aa.aa",
    "password":"U!6kbm7yG3lN",    
    "firstName":"   Rë   en  ",
    "surname":"Doe"
}

###

POST {{path}}/google
Content-Type: application/json

{
    "code":"asdasd"
}